apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: disaster-simulator-lrbg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: disaster-simulator-lrbg
    app.kubernetes.io/part-of: erdemo
  name: disaster-simulator-lrbg
  namespace: rhn-sa-sshaaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: disaster-simulator-lrbg
status:
  loadBalancer: {}
