apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: responder-service-quarkus-hlmr
  namespace: rhn-sa-sshaaf-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:rhn-sa-sshaaf-tenant-responder-service-quarkus-hlmr
        name: my-java-quarkus
        resources: {}
status: {}
