apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: responder-service-quarkus-hlmr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: responder-service-quarkus-hlmr
    app.kubernetes.io/part-of: erdemo
  name: responder-service-quarkus-hlmr
  namespace: rhn-sa-sshaaf-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: responder-service-quarkus-hlmr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: responder-service-quarkus-hlmr
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:rhn-sa-sshaaf-tenant-responder-service-quarkus-hlmr
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
