apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: erdemo
    appstudio.openshift.io/component: devfile-sample-hvvz
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-hvvz
  namespace: rhn-sa-sshaaf-tenant
spec:
  url: https://github.com/sshaaf/emergency-console
