apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mission-service-quarkus-gkuf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mission-service-quarkus-gkuf
    app.kubernetes.io/part-of: erdemo
  name: mission-service-quarkus-gkuf
  namespace: rhn-sa-sshaaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: mission-service-quarkus-gkuf
status:
  loadBalancer: {}
